import {
  defaultTheme,
  fonts,
  motion,
  opacity,
  primitives,
  radius,
  semanticTokenNames,
  themeNames,
  themes,
} from "./tokens";

/**
 * Renders tokens.ts as CSS for Tailwind 4: primitives as theme colours, semantic tokens as CSS variables per theme,
 * mapped to Tailwind utilities (bg-primary, text-critical…). `pnpm tokens` writes the result.
 */
export function renderTokensCss() {
  const lines: string[] = [
    "/* Generated by `pnpm tokens` from src/design-system/tokens.ts. Don't edit by hand. */",
    "",
    "@theme {",
    ...Object.entries(primitives).flatMap(([scale, steps]) =>
      Object.entries(steps).map(([step, hex]) => `  --color-${scale}-${step}: ${hex};`),
    ),
    "}",
    "",
    "@theme inline {",
    ...semanticTokenNames.map((name) => `  --color-${name}: var(--${name});`),
    `  --font-sans: ${fonts.sans};`,
    `  --font-heading: ${fonts.sans};`,
    `  --font-mono: ${fonts.mono};`,
    ...[
      ["sm", 0.6],
      ["md", 0.8],
      ["lg", 1],
      ["xl", 1.4],
      ["2xl", 1.8],
      ["3xl", 2.2],
      ["4xl", 2.6],
    ].map(([size, factor]) => `  --radius-${size}: calc(var(--radius) * ${factor});`),
    `  --ease-standard: ${motion["ease-standard"]};`,
    "}",
    "",
    ":root {",
    `  --radius: ${radius.base};`,
    `  --radius-button: ${radius.button};`,
    ...Object.entries(motion).map(([name, value]) => `  --${name}: ${value};`),
    ...Object.entries(opacity).map(([name, value]) => `  --opacity-${name}: ${value};`),
    "}",
  ];
  // the default theme also answers to plain :root; every theme is selected with data-theme="<name>" on <html>
  for (const theme of themeNames) {
    lines.push(
      "",
      `${theme === defaultTheme ? ":root,\n" : ""}:root[data-theme="${theme}"] {`,
      "  color-scheme: light;",
      ...semanticTokenNames.map((name) => `  --${name}: ${themes[theme][name]};`),
      "}",
    );
  }
  return lines.join("\n") + "\n";
}
