import {
  modeNames,
  motion,
  opacity,
  primitives,
  radius,
  semanticTokenNames,
  themeNames,
  themes,
  type ThemeName,
} from "./tokens";

/**
 * Renders tokens.ts as CSS for Tailwind 4: primitives as theme colours, semantic tokens as CSS variables per
 * theme × mode, mapped to Tailwind utilities (bg-primary, text-critical…). `pnpm tokens` writes the result.
 */
export function renderTokensCss() {
  const lines: string[] = [
    "/* Generated by `pnpm tokens` from src/design-system/tokens.ts. Don't edit by hand. */",
    "",
    "@theme {",
    ...Object.entries(primitives).flatMap(([scale, steps]) =>
      Object.entries(steps).map(([step, hex]) => `  --color-${scale}-${step}: ${hex};`),
    ),
    "}",
    "",
    "@theme inline {",
    ...semanticTokenNames.map((name) => `  --color-${name}: var(--${name});`),
    "  --font-sans: var(--font-geist-sans, ui-sans-serif, system-ui, sans-serif);",
    "  --font-mono: var(--font-geist-mono, ui-monospace, monospace);",
    "  --font-heading: var(--font-geist-sans, ui-sans-serif, system-ui, sans-serif);",
    ...[
      ["sm", 0.6],
      ["md", 0.8],
      ["lg", 1],
      ["xl", 1.4],
      ["2xl", 1.8],
      ["3xl", 2.2],
      ["4xl", 2.6],
    ].map(([size, factor]) => `  --radius-${size}: calc(var(--radius) * ${factor});`),
    `  --ease-standard: ${motion["ease-standard"]};`,
    "}",
    "",
    ":root {",
    `  --radius: ${radius.base};`,
    ...Object.entries(motion).map(([name, value]) => `  --${name}: ${value};`),
    ...Object.entries(opacity).map(([name, value]) => `  --opacity-${name}: ${value};`),
    "}",
  ];
  // Orange light is also the default before a theme is chosen; dark mode is the `dark` class on <html>
  const selector = (theme: ThemeName, mode: (typeof modeNames)[number]) => {
    const own = `:root${mode === "dark" ? ".dark" : ""}[data-theme="${theme}"]`;
    return theme === "orange" ? `:root${mode === "dark" ? ".dark" : ""},\n${own}` : own;
  };
  for (const mode of modeNames) {
    for (const theme of themeNames) {
      lines.push(
        "",
        `${selector(theme, mode)} {`,
        `  color-scheme: ${mode};`,
        ...semanticTokenNames.map((name) => `  --${name}: ${themes[theme][mode][name]};`),
        "}",
      );
    }
  }
  return lines.join("\n") + "\n";
}
